languageCode = "en"
languageName = "English"
languageDirection = "ltr"
timeZone = "Australia/ACT"
disqusShortname = "bennytek"
weight = 1

title = "Bennytek's Blog"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[author]
  name = "Bennytek"
  image = "me.png"
  headline = "Welcome to my blog!"
  # bio = "Like what?"
  links = [
  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/Bennytek" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
    { instagram = "https://instagram.com/Bennytek" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
    { lastfm = "https://last.fm/user/Bennytek" },
  #   { linkedin = "https://linkedin.com/in/username" },
    { mastodon = "https://aus.social/@Bennytek" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { spotify = "https://open.spotify.com/user/zr3pgugp68s0ysv4azmgmwiza" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    { steam = "https://steamcommunity.com/id/Bennytek/" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
    { twitch = "https://twitch.tv/Bennyttek" },
  #   { whatsapp = "https://wa.me/phone-number" },
    { x-twitter = "https://twitter.com/Bennyttek" },
    { youtube = "https://youtube.com/Bennytek" },
  ]
